DKAFC-6647: Configure remote copy / delete circuit breaker waitIntervalFunctionInOpenState to 5 mins (#19)
This pull request enhances the circuit breaker configuration for the
HDFS remote storage manager by introducing custom settings and improving
configuration validation. The changes ensure that only valid circuit
breaker states are accepted, and circuit breakers now use a randomized
wait interval when open to improve resilience.

T3-DKAFC-6647

### Test Plan
```
[udocker@/home/udocker/odin-kafka/bin #]sh kafka-configs.sh --bootstrap-server localhost:9092 --broker-defaults --alter --add-config remote.log.storage.hdfs.copy.circuit.breaker.state=xyz
Error while executing config command with args '--bootstrap-server localhost:9092 --broker-defaults --alter --add-config remote.log.storage.hdfs.copy.circuit.breaker.state=xyz'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidRequestException: Invalid value xyz for configuration hdfs.copy.circuit.breaker.state:  Valid values are: [FORCED_OPEN, CLOSED, DISABLED]
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2096)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:406)
	at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:354)
	at kafka.admin.ConfigCommand$.mainNoExit(ConfigCommand.scala:102)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:86)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.InvalidRequestException: Invalid value xyz for configuration hdfs.copy.circuit.breaker.state:  Valid values are: [FORCED_OPEN, CLOSED, DISABLED]
```