DKAFC-7004: Handle empty bucket cases in remote storage provider (#97)
- T3-DKAFC-7004
- This patch is required to remove the
`remote.log.storage.hdfs.default.file.system.uri` from Kafka DSC.
- See https://github.com/uber-code/data-dsc-builder/pull/272 for more
details


Error stacktrace while reading the data from remote storage when
`remote.log.storage.hdfs.default.file.system.uri` is set to empty:
```
[2026-04-23 05:10:46,717] 3470438 [remote-log-reader-7] ERROR kafka.log.remote.RemoteLogReader  - Error occurred while reading the remote data for 0cjzHMheTdmsULg0xmV2rA:test-hdfs-decomm-topic-0
java.lang.IllegalArgumentException: Unknown remote storage provider for bucket:
        at org.apache.kafka.rsm.hdfs.FileSystemManager.getRemoteStorageProvider(FileSystemManager.java:544)
        at org.apache.kafka.rsm.hdfs.HDFSRemoteStorageManager.fetchAuxiliaryFiles(HDFSRemoteStorageManager.java:417)
        at org.apache.kafka.rsm.hdfs.PrefetchEnabledHDFSRemoteStorageManager.fetchAuxiliaryFiles(PrefetchEnabledHDFSRemoteStorageManager.java:201)
        at org.apache.kafka.server.log.remote.storage.ClassLoaderAwareRemoteStorageManager.lambda$fetchAuxiliaryFiles$12(ClassLoaderAwareRemoteStorageManager.java:145)
        at org.apache.kafka.server.log.remote.storage.ClassLoaderAwareRemoteStorageManager.withClassLoader(ClassLoaderAwareRemoteStorageManager.java:90)
        at org.apache.kafka.server.log.remote.storage.ClassLoaderAwareRemoteStorageManager.fetchAuxiliaryFiles(ClassLoaderAwareRemoteStorageManager.java:145)
        at org.apache.kafka.storage.internals.log.RemoteIndexCache.createCacheEntry(RemoteIndexCache.java:411)
        at org.apache.kafka.storage.internals.log.RemoteIndexCache.lambda$getIndexEntry$11(RemoteIndexCache.java:396)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.lambda$doComputeIfAbsent$14(BoundedLocalCache.java:2406)
        at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.doComputeIfAbsent(BoundedLocalCache.java:2404)
        at com.github.benmanes.caffeine.cache.BoundedLocalCache.computeIfAbsent(BoundedLocalCache.java:2387)
        at com.github.benmanes.caffeine.cache.LocalCache.computeIfAbsent(LocalCache.java:108)
        at com.github.benmanes.caffeine.cache.LocalManualCache.get(LocalManualCache.java:62)
        at org.apache.kafka.storage.internals.log.RemoteIndexCache.getIndexEntry(RemoteIndexCache.java:396)
        at org.apache.kafka.storage.internals.log.RemoteIndexCache.lookupOffset(RemoteIndexCache.java:458)
        at kafka.log.remote.RemoteLogManager.lookupPositionForOffset(RemoteLogManager.java:2049)
        at kafka.log.remote.RemoteLogManager.read(RemoteLogManager.java:1981)
        at kafka.log.remote.RemoteLogReader.lambda$call$0(RemoteLogReader.java:67)
        at com.yammer.metrics.core.Timer.time(Timer.java:91)
        at kafka.log.remote.RemoteLogReader.call(RemoteLogReader.java:67)
        at kafka.log.remote.RemoteLogReader.call(RemoteLogReader.java:37)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:840)
  ```