DKAFC-5111: Enable tiered storage disablement validation in ZK mode
Summary:
# In upstream, tiered storage disablement is supported only in the Kraft mode. The ZK mode development is frozen.
# In Kraft mode, the topic config validation is done by the controller ([[ https://sg.uberinternal.com/code.uber.internal/uber-code/data-kafka@3.9.x-dev/-/blob/core/src/main/scala/kafka/server/ControllerConfigurationValidator.scala?L111 | ControllerConfigurationValidator ]])
# In D15448903, we have added the support to enable tiered storage disablement in ZK mode. But, we missed adding the respective validations. This can confuse the user whether the tiered storage is disabled or not for a topic as it does not propagate the exception back to the caller. With this diff, the validations are enabled.

Test Plan:
Unit test and tested out the validation by running the setup locally:

Before the patch:
```
% sh kafka-configs.sh  --bootstrap-server localhost:9092 --topic apple --add-config remote.storage.enable=false --alter
Completed updating config for topic apple.

# server logs
[2025-02-03 13:04:22,953] 3935403 [/config/changes-event-process-thread] ERROR kafka.common.ZkNodeChangeNotificationListener  - error processing change notification {"version":2,"entity_path":"topics/apple"} from /config/changes/config_change_0000010826
org.apache.kafka.common.errors.InvalidConfigurationException: It is invalid to disable remote storage without deleting remote data. If you want to keep the remote data and turn to read only, please set `remote.storage.enable=true,remote.log.copy.disable=true`. If you want to disable remote storage and delete all remote data, please set `remote.storage.enable=false,remote.log.delete.on.disable=true`.

```

After the patch:
```
% sh kafka-topics.sh --create --topic orange --partitions 1 --replication-factor 1 --bootstrap-server localhost:9092 \
    --config remote.storage.enable=true --config local.retention.ms=60000 --config retention.ms=7200000 \
    --config local.retention.bytes=1048576 --config retention.bytes=10485760 \
    --config segment.bytes=10485760 --config file.delete.delay.ms=1000
Created topic orange.

% sh kafka-configs.sh --bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=false --alter
Error while executing config command with args '--bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=false --alter'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: It is invalid to disable remote storage without deleting remote data. If you want to keep the remote data and turn to read only, please set `remote.storage.enable=true,remote.log.copy.disable=true`. If you want to disable remote storage and delete all remote data, please set `remote.storage.enable=false,remote.log.delete.on.disable=true`.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2028)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:382)
	at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:349)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:98)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: It is invalid to disable remote storage without deleting remote data. If you want to keep the remote data and turn to read only, please set `remote.storage.enable=true,remote.log.copy.disable=true`. If you want to disable remote storage and delete all remote data, please set `remote.storage.enable=false,remote.log.delete.on.disable=true`.

% sh kafka-configs.sh --bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=true,remote.log.copy.disable=true --alter
Error while executing config command with args '--bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=true,remote.log.copy.disable=true --alter'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: When `remote.log.copy.disable` is set to true, the `local.retention.bytes` and `retention.bytes` must be set to the identical value because there will be no more logs copied to the remote storage.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2028)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:382)
	at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:349)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:98)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: When `remote.log.copy.disable` is set to true, the `local.retention.bytes` and `retention.bytes` must be set to the identical value because there will be no more logs copied to the remote storage.

% sh kafka-configs.sh --bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=true,remote.log.copy.disable=true,local.retention.bytes=10485760 --alter
Error while executing config command with args '--bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=true,remote.log.copy.disable=true,local.retention.bytes=10485760 --alter'
java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.InvalidConfigurationException: When `remote.log.copy.disable` is set to true, the `local.retention.ms` and `retention.ms` must be set to the identical value because there will be no more logs copied to the remote storage.
	at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
	at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2028)
	at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
	at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:382)
	at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:349)
	at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:98)
	at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Caused by: org.apache.kafka.common.errors.InvalidConfigurationException: When `remote.log.copy.disable` is set to true, the `local.retention.ms` and `retention.ms` must be set to the identical value because there will be no more logs copied to the remote storage.

% sh kafka-configs.sh --bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=true,remote.log.copy.disable=true,local.retention.bytes=10485760,local.retention.ms=7200000 --alter
Completed updating config for topic orange.

% sh kafka-configs.sh --bootstrap-server localhost:9092 --topic orange --add-config remote.storage.enable=false,remote.log.delete.on.disable=true --alter
Completed updating config for topic orange.
```

Reviewers: shonali, abhijeek, #ldap_kafka_admins

Reviewed By: abhijeek, #ldap_kafka_admins

Revert Plan: git revert

JIRA Issues: DKAFC-5111

API Changes: NA

Monitoring and Alerts: NA

Differential Revision: https://code.uberinternal.com/D16430311